stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - testserver-vps
  script:
    - echo "JWT_KEY=$JWT_KEY" > .env
    - docker compose -p netgroupback up --build --remove-orphans --detach
